default:
  image: node:16.13.0

stages:
  - build
  - test
  - deploy

build-server:
  stage: build
  before_script:
    - npx yarn install
  script:
    - npx yarn server run build
  artifacts:
    untracked: true
    paths:
      - projects/server/dist
  only:
    changes:
      - projects/server/**/*
      - projects/common/**/*
      - .gitlab-ci.yml

deploy-dev-server:
  stage: deploy
  image: ruby:latest
  needs: [ build-server ]
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=on-it-api-dev --api-key=$HEROKU_API_KEY
  only:
    refs:
      - dev
    changes:
      - projects/server/**/*
      - projects/common/**/*


deploy-server:
  stage: deploy
  image: ruby:latest
  needs: [ build-server ]
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=on-it-api --api-key=$HEROKU_API_KEY
  only:
    refs:
      - master
    changes:
      - projects/server/**/*
      - projects/common/**/*

pages:
  stage: deploy
  before_script:
    - npx yarn install
  script:
    - npx yarn build
    - npx yarn site build
    - rm -rf public
    - cp projects/site/build/index.html projects/site/build/404.html
    - mv projects/site/build public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
    changes:
      - projects/common/**/*
      - projects/site/**/*
      - .gitlab-ci.yml
