default:
  image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - npx yarn install

build-common:
  stage: build
  script:
    - npx yarn common run build
  artifacts:
    untracked: true
    paths:
      - common/lib

build-server:
  stage: build
  script:
    - npx yarn server run build
  artifacts:
    untracked: true
    paths:
      - server/dist
      - server/Procfile

deploy-server:
  stage: deploy
  image: ruby:latest
  needs: [build-server]
  script:
    - cd server
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=on-it-api --api-key=$HEROKU_API_KEY
  only:
    refs:
      - master
