default:
  image: node:latest

stages:
  - build
  - test
  - deploy

build-server:
  stage: build
  script:
    - cd server
    - npm install
    - npm run build-full
  artifacts:
    untracked: true
    paths:
      - dist/
      - Procfile

deploy-server:
  stage: deploy
  image: ruby:latest
  needs: [build-server]
  dependencies:
    - build
    - docs
  script:
    - cd server
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=boil --api-key=$HEROKU_API_KEY
  only:
    refs:
      - master
